pipeline {
    //Declaration of the agent that will be responsible for executing the stages of the pipeline
    agent any

    // Declaration of the environment variables necessary for the execution of the pipeline
    environment {
        SONARQUBE_HOST_URL = 'http://sonarqube-server:9000' // URL del servidor de SonarQube
        SONAR_ORG = 'medinafdzz' // en caso de usar SonarQube cloud

        //Auth tokens
        SONARQUBE_AUTH_TOKEN = credentials('sonarqube-token')
        GITHUB_AUTH_TOKEN = credentials('github-token')
    }

    // Definition of the stages of the pipeline
    stages {
        stage('Stage 0 - Environment setup') {
            steps {
                //Verificar la instalacion correcta
                sh 'python3 --version'
                sh 'node --version'
            }
        }
        stage('Stage 1 - Download the repository and run SonarQube analysis') {
            steps {
                echo 'In this stage, it downloads the repository that makes the webhhok'
                checkout scm

            script {
                // Get the name of the remote repo
                // (basename is used to get the name of the repo without the .git extension)
                env.REPO_NAME = sh(
                    script: 'basename $(git config --get remote.origin.url) .git',
                    returnStdout: true
                ).trim()

                env.SONARQUBE_PROJECT_KEY = env.REPO_NAME.replace('/', '_')
            }
                echo "Repository name: ${REPO_NAME}"

                echo 'Compiling the Java example code for SonarQube analysis'

                echo 'Sonarqube analysis'
                echo 'Execution of the SonarQube Scanner to analyze the code'
                withSonarQubeEnv('SonarQube-Server') {
                    sh """
                     sonar-scanner \
                     -Dsonar.projectName=${env.REPO_NAME} \
                     -Dsonar.projectKey=${env.SONARQUBE_PROJECT_KEY} \
                     -Dsonar.sources=. \
                     -Dsonar.exclusions=**/node_modules/**,**/vendor/**,**/*.md,**/*.txt,**/*.json \
                    """
                }
                echo 'Here SonarQube will measure the code quality'
            }
        }
        stage('Stage 2 - Preparation of the credentials and execution of the IA agent') {
            steps {
                echo 'Load of the credentials for SonarQube, GitHub and the LLM in environment variables'
                withCredentials([
                    string(credentialsId: 'sonarqube-token', variable: 'SONARQUBE_AUTH_TOKEN'),
                    string(credentialsId: 'github-token', variable: 'GITHUB_AUTH_TOKEN'),
                    string(credentialsId: 'LLM-token', variable: 'LLM_AUTH_TOKEN')
                    ]) {
                    echo 'AI agent execution'

                    sh '''
                        pip install requests google-generativeai --break-system-packages || \
                        pip install requests google-generativeai
                    '''

                    sh "python3 agent.py ${env.REPO_NAME}"
                    }
            }
        }
    }
        //Delete the temporary files generated by the pipeline
        post {
            always {
                echo 'Cleaning the temporary files generated by the pipeline'
                deleteDir()
            }
        }
}
